AWSTemplateFormatVersion: 2010-09-09
Description: "Security Group Stack"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: SecurityGroup
        Parameters:
          - EnvironmentName
          - Environment
          - VpcId
          - SgIngCidrIp3389
          - ClientIpv4Cidr

Parameters:
  EnvironmentName:
    Type: String
    Default: "EnvironmentName"
    Description: "Name of the Security Group"

  Environment:
    Description: "Select the environment."
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "ID of the VPC"

  ClientIpv4Cidr:
    Type: String
    Default: "0.0.0.0/0"
    Description: "ClIENT CIDR IP range for ingress traffic"

  SgIngFromPort3389:
    Type: String
    Default: "3389"
    Description: "Port number for Remort Desktop traffic"

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # -------------------------------------
  # EC2 SecurityGroup
  # -------------------------------------
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ec2-${EnvironmentName}-${Environment}
      GroupDescription: EC2 of the Security Group
      VpcId: !Ref VpcId
      # -------------------------------------
      # EC2 inbound rule
      # -------------------------------------
      SecurityGroupIngress:
        - CidrIp: !Ref ClientIpv4Cidr
          FromPort: !Ref SgIngFromPort3389
          IpProtocol: tcp
          ToPort: !Ref SgIngFromPort3389
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
